### PR TITLE
Created README with project members and description

### PR DESCRIPTION
**Pull request by evalverde95**
Added the README file with the project members and description, according to the specified instructions.

### CODE REVIEW

**Comment by Riki-Jimenez** [comment]
Todo bien

**Review by Riki-Jimenez — COMMENTED** [review]
Prueba en review changes

**Review by dmeseguerw — COMMENTED** [review]
Muy bien!

**Comment by LauraRincon** [comment]
Agree 👍🏼

**Review by LauraRincon — COMMENTED** [review]
nice job

**Pull request merged**
